export const NEW_JWT_TOKEN = 'NEW_JWT_TOKEN';
export const CLEAR_JWT_TOKEN = 'CLEAR_JWT_TOKEN';
export const SET_ACCESS_LEVEL = 'SET_ACCESS_LEVEL';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_USER_ID = 'SET_USER_ID';
